epoll_socket:
	gcc -Wall -o epoll_socket epoll_socket.c

pipe:
	gcc -Wall -o pipe pipe.c

pthread_key_create:
	gcc -Wall -o pthread_key_create pthread_key_create.c -lpthread

clean:
	rm -rf epoll_socket pipe pthread_key_create
